### ISSUE TITLE
Make it possible to send eth from your wallet to any address

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#149]

**Comment by vsimetka** [comment]
I believe the idea was to be able to build a view that would allow you to sent ETH from your wallet to any address outside of the Dapp.

**Comment by satyavh** [comment]
changed the title :-)

**Comment by vsimetka** [comment]
Stil todo:

- [ ] Transaction confirmation before sending the money.
- [ ] Checking the recipient address is valid.
- [ ] Updating the balance after the transaction is sent.

**Comment by satyavh** [comment]
I fixed loading the gas price. 

Regarding 'Transaction confirmation before sending the money.', we have a story for that to do that for all transactions in the dapp. I suggest creating some kind of 'middleware' popup for that.

`Checking the recipient address is valid.` -> You can do that with `validations="isEtherAddress"`

**Comment by vsimetka** [comment]
@perissology how is the balance updated? Can it be observed because for now it seems that it only updates after refresh.

**Comment by perissology** [comment]
look at `getWeb3.js` there is a `getBalance` method that should be updating the balance every block. 

That may not be working correctly.

**Comment by vsimetka** [comment]
The balance actually is not updated even after donating.

**Comment by vsimetka** [comment]
I have decided to take the balance updating out of this issue and create #188 . I consider withdrawing as finished, @satyavh @perissology can you review this and close?
