### ISSUE TITLE
Design UI for new milestone creation 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1730]
Design UI of new milestone propose pages according to below figma design. The page will be shown after user clicks propose/create milestone in a campaign

https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2072%3A841&viewport=135%2C115%2C0.5314952731132507&scaling=min-zoom

#1214

**Comment by aminlatifi** [comment]
@MohammadPCh These are the first ones of the whole new pages which will replace current UI of giveth 1.
You have freedom to chose another UI framework library (Ant Design, Material UI, etc.), so it should be a futuristic decision. We can discuss it if you like.

**Comment by aminlatifi** [comment]
@MohammadPCh in case you have any question regarding the design @markoprljic is our UX designer.

**Comment by MohammadPCh** [comment]
Dear @markoprljic,
Thanks for your professional design. I have some questions about your design like:
- Can I have dimension of elements you have designed?
- If we like to be responsive, we need to have a specific design for each breakpoint (xs.sm.md,lg,XL)
- You have designed 8 perfect pages. Are these pages have separate route or all of them are modals and user will see them in milestone/campaign page?
- We have receipt part in forms. The title should be receipt or image?
- In old design in description part we have editor that user can upload images, in new design we have simple box that only accept text. Is it OK?
 
Thanks.

**Comment by markoprljic** [comment]
Hi Cherik, please refer to the prototype in Figma https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2072%3A841&viewport=416%2C64%2C0.09111352264881134&scaling=min-zoom

> * Can I have dimension of elements you have designed?
If you inspect within Figma you will see all sizes including css code.

> * If we like to be responsive, we need to have a specific design for each breakpoint (xs.sm.md,lg,XL)
I leave this for you to scale linearly for mobile.

> * You have designed 8 perfect pages. Are these pages have separate route or all of them are modals and user will see them in milestone/campaign page?
I'm not sure I understand the question. These are not modals but standalone pages. The flow is shown in the Figma.
Let me know if something isn't clear.

> * We have receipt part in forms. The title should be receipt or image?
Yes.
> * In old design in description part we have editor that user can upload images, in new design we have simple box that only accept text. Is it OK?
>    
I assume yes, but if we already have text editor built in then include it.

**Comment by aminlatifi** [comment]
@MohammadPCh Please see the comments in the figma

**Comment by markoprljic** [comment]
@aminlatifi @MohammadPCh I made small changes in Figma based on Griff's comments from yesterday's call. Please make sure to read the comments for further instructions.

**Comment by aminlatifi** [comment]
Default images for `Bounty` and `Expenses` https://github.com/Giveth/giveth-dapp/issues/1831

**Comment by aminlatifi** [comment]
@MohammadPCh Please fix these remained sub issues:
- [ ] Click in whole part of description input should focus on it
- [ ] Fix style of input number including: size, removing step buttons, adding thousands separator
- [ ] Make form complete

**Comment by aminlatifi** [comment]
@markoprljic Figma content is not available, is there any way to see Giveth TRACE design? It would be better for @MoeNick to have access to them

**Comment by markoprljic** [comment]
@aminlatifi @MoeNick Here is the Figma source file https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=2072%3A827
