### ISSUE TITLE
Support injected web3 instances

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#174]
Currently we only support the `GivethWallet`. We should default to the injected web3 (metamask/ mist/toshi/etc), and use the `GivethWallet` as a fallback when on devices that can support upload/downloading of a json file.

TODO:

- [ ] wallet abstraction we can use throughout the dapp to abstract the differences between the js giveth wallet and the injected web3 instances.
- [ ] need to be able to sign messages as this is used for login
- [ ] need to be able to send transactions
- if device doesn't support json file upload (ios, etc) and injected web3 is not found
  - [ ] only allow the user to view the dapp
  - [ ] inform the user of how they can interact with the dapp (ex. use toshi/status on mobile)

bonus:
- [ ] display a warning if tx isn't sent.
    - with metamask, and possibly others... sometimes when sending a tx, metamask doesn't register/display the confirmation screen. It would inform the user when this happens and tell them to check metamask, etc

hopefully we don't run into any issues with the fact that we're using web3 1.0. The injected providers may not support 1.0

**Comment by vojtechsimetka** [comment]
Implemented by @perissology in a slightly different way. Users now have to donate with injected web3 instance but for interacting with the DApp GivethWallet is used. This is best option for time being as we use 2 networks.
