### ISSUE TITLE
Track the gas paid for every account on the backend

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1921]
Every time there is a payment, we pay tx fees twice... once for each payment that is paid by our bridge key, and then the security guard usually makes a bulk payment and sends the money out of the bridge for multiple payments

We should track the USD value and ETH Value of the gas cost for each tx and so that we can communicate the amount of gas that we have paid to the users.

This will make paying the gas worth it! 

We will want this info to be aggregated for each of these  
- [x] recipient (To be displayed in the profile page?)
- [x] campaign (To be displayed on the Campaign Page
- [x] milestone (To be displayed on the Milestone page)

**Comment by MoeNick** [comment]
@MoeNick get feed back from @markoprljic
