### ISSUE TITLE
add my-milestones page

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#24]
should show current state and available actions for any milestones I'm involved with. This can be as a reviewer or recipient.

1. ~~do we need the "maker" and "fundraiser" roles (https://drive.google.com/drive/folders/0BzJyIRYTXoqUaXh1b1RDYlplQlE & https://drive.google.com/drive/folders/0BzJyIRYTXoqUaXh1b1RDYlplQlE)~~
2. ~~do we have the accept/propose flow~~
3. ~~arbitrator?~~

- [x] set maxAmount (funding limit)
- [x] mark milestone complete
- [x] cancel milestone
- [x] approve completed milestone
- [x] reject completed milestone
- [x] withdraw

**Comment by satyavh** [comment]
isn't maxAmount a property of the milestone? Should that not be changed by editing a milestone?

**Comment by perissology** [comment]
yep. I just kinda used this issue to list everything I thought was missing regarding milestones

**Comment by perissology** [comment]
okay, this is mostly done, however there are a few bugs in liquidPledging that are holding this back.

1. when canceling a milestone w/ donations, the donations are not returned to the previous owner.

2. when withdrawing, the withdraw amount is always set to 0, not the amount the milestone owns

**Comment by vsimetka** [comment]
Seems to be working in develop branch, may I close @perissology ?
