### ISSUE TITLE
Create Error Component

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#298]
Simple draft already created in feature/errorrHandling branch.

**Task**
Create an error popup component visually similar to the Oh no! popup you can find in https://github.com/Giveth/giveth-dapp/blob/develop/src/components/views/MyMilestones.jsx#L199 . This component should be designed as follows:

- [ ] Manually created error message to be displayed to user.
- [ ] Exception object input that is not visible to the user.
- [ ] It should have a "Report error" button. When clicked, the error message from the exception object along with stack trace should be uploaded to feathers and/or distributed to email addresses specified in the configuration.js file.
- [ ] Close button.

Once such component is created, it should be added to all the catch blocks and onError handlers.

**Comment by GriffGreen** [comment]
The error component is 1/2 way built but paused, it should be added to all the catch blocks and onError handlers.... If someone can pick this up and add this to allllllll of the DApp, the Gov Campaign will give a Bounty of 0.5 ETH... This is a big project, it will require a conversation with @vojtechsimetka before tackling in earnest.
