### ISSUE TITLE
Show # of confirmations for pending dac/campaigns/milestone, etc

### ISSUE THREAD

**Issue by ewingrj** [Giveth/giveth-dapp#342]
For all of the following views

MyDacs
MyCampaigns
MyMilestones
MyDelegations
MyDonations

If the status is pending, we should show the current # of confirmations and the # of required confirmations. This data should all be present in the return models from feathers.

**Comment by cbrenn** [comment]
Working on this issue now. 

Could you explain conceptually what a confirmation is? 

I think that it is a reviewer must confirm the campaign is valid before it can be launched and this confirmation takes place on the reviewer page. 

I'm thinking about making it a property of the campaign model, but I don't see it stored anywhere currently.

**Comment by perissology** [comment]
a confirmation is just the number of blocks passed when the tx was mined. If it was mined 2 blocks ago, then there are 2 confirmations.

This data is already present on the model returned from feathers, you only need to show it in the ui

**Comment by vojtechsimetka** [comment]
Hi @cbrenn, thank you for your interest. See perissology response. Will you take this up? If so let me know. I was just about to assign this to @xavivives

**Comment by cbrenn** [comment]
Coming along with this, and should be finished by Sunday. The only place I really see a clear confirmation state is in the Donation Model. Everything else I am assuming I take from the model directly, unsure about changing the constructor params for campaign, milestones etc. 
Please let me know if that is ok.

**Comment by vojtechsimetka** [comment]
Please go ahead and modify the other models. The required data should be received from feathers, but they are not added to the other models.

**Comment by cbrenn** [comment]
Confirmations seem to be attached to the idea of a transaction. Milestones and delegations don't seem to be mapped to the idea of a transaction. Also they don't have a model in the D'app and therefore don't take in confirmations or required confirmations as state. Not seeing a logical way to get transactions from milestones or delegations...something I'm missing?

**Comment by perissology** [comment]
every action taken on a milestone (mark complete, reject, etc) is a tx and the txhash & # of confirmations on the milestone is updated.

For delegations, the txhash & # of confirmations is updated on the donation that is delegated

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 100.0 DAI (100.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $55,066.53 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now.
Please review their action plans below:


**1) [anshumanv](https://gitcoin.co/profile/anshumanv) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=approve&worker=anshumanv) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=reject&worker=anshumanv))_.**

Have worked on a bunch of bounties in this project, can get this done pretty quick typical react issue.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks, 1 day from now.
Please review their action plans below:


**1) [eswarasai](https://gitcoin.co/profile/eswarasai) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=approve&worker=eswarasai) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=reject&worker=eswarasai))_.**

Will look into the current behaviour of pending transactions and update the UI to display # of block confirmations accordingly

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419).

**Comment by GriffGreen** [comment]
@eswarasai At one point this was working... we should be able to add a column.... @ewingrj will make a comment

**Comment by ewingrj** [comment]
note: the backend should have all the confirmation info already attached to entity

props:

`requiredConfirmations: 6`
`confirmations: 6`

**Comment by eswarasai** [comment]
@ewingrj -- Okay. I think there's a little confusion here on the intended behaviour of the existing code. Below is the behaviour that I've seen. Let me know what exactly needs to be changed and where.

1) Made a donation for `DAC Rocky Mountain National Commons`
2) In the list of `My Donations`, I was able to see the pending state of the transactions
3) A column for `confirmations` is displayed as `0/6` for pending and `6/6` for already confirmed transactions as you can see in the below screenshot

<img width="1084" alt="screenshot 2019-02-27 at 12 03 20 pm" src="https://user-images.githubusercontent.com/5172086/53470597-23143180-3a88-11e9-81ba-c9a915dcc6c3.png">

4) Although, the transaction has already been confirmed on the network, it really took a while to get the confirmation from `feathersClient` via the `DonationProvider`
5) Once the transactions is confirmed, the `confirmations` column is hidden as per the logic in the view

Couple of questions on the above behaviour:
1) For pending transaction, I couldn't find `confirmations` key in the data returned by `feathersClient`. Once the transaction is confirmed, I was able to see the `confirmations` key with the value as `6`. There's no intermediary value update for `confirmations` between `1` to `5`. Is this expected?
2) Would you want to have the Confirmations column to be displayed always irrespective of the transaction status? Currently, it's being displayed only if there's a pending transaction in the data

Thanks!

**Comment by ewingrj** [comment]
> For pending transaction, I couldn't find `confirmations` key in the data returned by `feathersClient`. Once the transaction is confirmed, I was able to see the `confirmations` key with the value as `6`. There's no intermediary value update for `confirmations` between `1` to `5`. Is this expected?

Correct, the confirmations are only added once the tx has been mined. So for pending tx, we can just say 0 confirmations. The confirmations should be updated on the backend, but the data in the ui may not be reactive, so the ui only doesn't reflect the intermediary values.

> Would you want to have the Confirmations column to be displayed always irrespective of the transaction status? Currently, it's being displayed only if there's a pending transaction in the data

I don't see the point of showing the column if there are no pending txs. I think keeping the current behavior would be best

**Comment by eswarasai** [comment]
@ewingrj -- Understood. So the issue here is data in the UI not being reactive and I need to ensure that the `feathersClient` is propagating the intermediary values to the UI. Please do confirm. Thanks!

**Comment by ewingrj** [comment]
yes, and confirm that all views in the op show the confirmations for pending txs

**Comment by gitcoinbot** [comment]
@eswarasai Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@eswarasai due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by GriffGreen** [comment]
Hey @eswarasai if you have any issues or are stuck on something feel free to join the riot chat and ask there: https://riot.im/app/#/room/!pJNSuPMvcrDttmJFvV:matrix.org?via=matrix.org&via=giveth.io&via=status.im

And you are also invited to our DApp meetings which happen at 6 pm Barcelona time every Friday ;-D

**Comment by zzyyxxww** [comment]
is this still open for work?

**Comment by GriffGreen** [comment]
@zzyyxxww YEAH! it is! if you have any issues or are stuck on something feel free to join the riot chat and ask there: https://riot.im/app/#/room/!pJNSuPMvcrDttmJFvV:matrix.org?via=matrix.org&via=giveth.io&via=status.im

And you are also invited to our DApp meetings which happen at 7 pm Barcelona time every Monday at https://meet.jit.si/giveth-dapp ;-D

**Comment by arbreton** [comment]
are you working on this one @zzyyxxww ?

**Comment by GriffGreen** [comment]
the story is that the various views are missing the confirmations that some of the views have

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 months, 3 weeks ago.
Please review their action plans below:


**1) [kris30pl](https://gitcoin.co/profile/kris30pl) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=approve&worker=kris30pl) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?mutate_worker_action=reject&worker=kris30pl))_.**

i dont know how to submitt my work

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419).

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by aminlatifi** [comment]
I am working on this and UI updates # confirmations for MyDacs, MyCampaigns and MyMilestones. For supporting MyDelegations feathers service should be changed. Feathres add # confirmations by a hook which uses foreign network txHash to obtain # confirmations.
Working on MyDelegations...

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by gitcoinbot** [comment]
@kris30pl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419?snooze=100)

**Comment by GriffGreen** [comment]
I think this issue is there now
