### ISSUE TITLE
Milestones that have no funding get marked complete and then can't receive funding

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#475]
There are many solutions to this very common error. 
Options:
1. Milestones cannot be marked complete unless they have some funding
2. If a Milestone has no funding an extra warning box comes up when marking it complete
3. **Even if a milestone is marked complete, the UI allows for funds to be sent to it.**

Each of these has its own pros and cons... My fave is 2 but any solution including one not listed here is fine :-D

**Comment by krrisis** [comment]
You should also delete Milestones that are now marked complete and have no funding as they now just appear double in the DApp which is quite confusing. Or.. create the option for us to delete these. thx!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [millnitzluan](https://gitcoin.co/profile/millnitzluan) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?mutate_worker_action=approve&worker=millnitzluan) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?mutate_worker_action=reject&worker=millnitzluan))_.**

As I'm going to start the other issue, I think that I can help in this one

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417).

**Comment by vojtechsimetka** [comment]
To whoever starts working on this: please implement option 3. All the way until Paid it should be able to receive money. Unless the smart contract does not allow it @perissology ? I don't think there is such restriction. https://github.com/Giveth/lpp-milestone/blob/master/contracts/LPPMilestone.sol

**Comment by millnitzluan** [comment]
@vojtechsimetka The donate button will appear even if the milestone has been fully funded?

**Comment by vojtechsimetka** [comment]
no, when the fullyFunded === true it should nod be displayed. Please use that flag on the milestone response. E.g. here https://github.com/Giveth/giveth-dapp/blob/ff091bf43c86630fa2e74cebe6ec04d8c7cfb9ba/src/components/views/ViewMilestone.jsx#L85

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 75.0 DAI (75.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@millnitzluan](https://gitcoin.co/profile/millnitzluan)



@mkosowsk please take a look at the submitted work:
* [PR](https://github.com/Giveth/giveth-dapp/pull/501) by @millnitzluan

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $45,760.19 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by mkosowsk** [comment]
Hi @millnitzluan, is there an update on this PR? Thanks! 👍

**Comment by millnitzluan** [comment]
@mkosowsk, I'm working on that

**Comment by krrisis** [comment]
hey @millnitzluan finding a solution for this one? Or should we open this up again? Thanks!!

**Comment by millnitzluan** [comment]
@krrisis I've stopped the work on gitcoin and said it on the PR, I couldn't find the solution.

**Comment by icole** [comment]
Is this still an issue that might be good for a first time contributor? Would be interested in taking a crack at it if so.

**Comment by GriffGreen** [comment]
Yeah @icole Would love to see some action on this issue... its been a thorn in my side for too long! We are all just getting out of some conferences.. @vojtechsimetka will probably be around to authorize work on this soon :-D if you need a more specific understanding of this... ping @griffgreen:matrix.org on https://riot.im/app/#/room/#giveth-product-development:matrix.org

**Comment by GriffGreen** [comment]
man... i swear this happens to me 3 times a month minimum... sooooo many people do this and it is sooooooo annoying :-( what do we gotta do to finish this

**Comment by vojtechsimetka** [comment]
This is fixed since #81 .

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by RichardZhu123** [comment]
Work in Progress - Didn't receive notification from GitCoin that the request had been approved and the my started bounties page is blank for me in GitCoin. Sorry about that!

**Comment by ewingrj** [comment]
there is nothing to work on. it's already fixed. not sure why gitcoinbot commented here. sorry about that

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by gitcoinbot** [comment]
@richardzhu123 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/475/1417?snooze=100)

**Comment by krrisis** [comment]
@gitcoinbot could you plz close this? thank you!
