### ISSUE TITLE
Milestone and Campaign Reviewer management

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#489]
**Description:**
The smart contracts allow for the Milestone and Campaign reviewer to be changed. To change reviewer, one has to call tho action `Change Reviewer` (called by old reviewer) and `Accept New Reviewer` (called by new reviewer). These should be two buttons in the UI.

**Task:**
- [ ] Add `Change Reviewer` button  for Campaigns https://github.com/Giveth/lpp-campaign/blob/master/contracts/LPPCampaign.sol#L103 . This button should be visible only for current Campaign reviewer and should open a popup in which the reviewer can select new one from the reviewer whitelist. Calling this action should dispatch email to the newly nominated reviewer.
- [ ] Add `Accept Reviewer Role` button for Campaigns https://github.com/Giveth/lpp-campaign/blob/master/contracts/LPPCampaign.sol#L108 .
- [ ] Add `Change Reviewer` button for Milestones https://github.com/Giveth/lpp-milestones/blob/lp-1.0.0/contracts/Milestone.sol#L130
~~- [ ] Add `Accept Reviewer Role` button for Milestones https://github.com/Giveth/lpp-milestone/blob/master/contracts/LPPMilestone.sol#L95~~
- [ ] When Milestone reviewer is changed, it should be registered in the milestone status updates
<img width="1286" alt="screen shot 2018-10-04 at 23 27 32" src="https://user-images.githubusercontent.com/7974813/46504078-1cf98c00-c82d-11e8-8e4a-43c70b5e8a77.png">

**Work time estimate:**
5-10h

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 DAI (300.0 USD @ $1.0/DAI)  attached to it__ as part of the Ethereum Community Fund via ECF Web 3.0 Infrastructure Fund fund__.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $48,592.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [cryptomental](https://gitcoin.co/profile/cryptomental) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=approve&worker=cryptomental) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=reject&worker=cryptomental))_.**

Hi. I would like to start working on this bounty after I finish with milestone donations. Estimated PR Wednesday EOD.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [cryptomental](https://gitcoin.co/profile/cryptomental) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=approve&worker=cryptomental) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=reject&worker=cryptomental))_.**

Hi. I would like to start working on this bounty after I finish with milestone donations. Estimated PR Wednesday EOD.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401).


**2) [toya999](https://gitcoin.co/profile/toya999) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=approve&worker=toya999) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?mutate_worker_action=reject&worker=toya999))_.**

Qhhejmkjiqujqnhh3huuwmmmqk84 ggwhq vwukjwgcyjk1nh

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401).

**Comment by gitcoinbot** [comment]
@cryptomental Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@cryptomental Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by cryptomental** [comment]
Hi! My giveth milestone donations bounty takes me more time than I had expected and I would like to be fair and not to block this bounty to others. I will therefore press 'stop' button on GitCoin to unblock it.

**Comment by iamonuwa** [comment]
@vojtechsimetka I would love to pick up this task. I've started work already on this.

**Comment by cryptomental** [comment]
Hi @iamonuwa it is great that you picked it up immediately. All the best with the bounty!

**Comment by vojtechsimetka** [comment]
@iamonuwa please feel free to work on this. This milestone was funded by ECF so @mkosowsk needs to approve you. Thanks again for the funding!

**Comment by iamonuwa** [comment]
@vojtechsimetka am getting 
`{ code: -32603, message: "gas required exceeds allowance or always failing transaction" }` when am sending a request to changeReviewer() (https://github.com/Giveth/lpp-campaign/blob/master/contracts/LPPCampaign.sol#L103)

**Comment by iamonuwa** [comment]
@vojtechsimetka are you there?

**Comment by vojtechsimetka** [comment]
Hi, what are the params that you are passing to the contract? Also did you try to increase the gas limit for that tx?

**Comment by iamonuwa** [comment]
@vojtechsimetka am passing the newReviewer address as requested by the LPPCampaign. I did not increase the gas limit

**Comment by iamonuwa** [comment]
@vojtechsimetka are you there?

**Comment by vojtechsimetka** [comment]
@iamonuwa try adding extra gas like here. https://github.com/Giveth/giveth-dapp/blob/237a8d70c7d54e8f796a8972c189dd02c64a3a9a/src/services/DonationService.js#L129

**Comment by iamonuwa** [comment]
> @iamonuwa try adding extra gas like here.
> 
> [giveth-dapp/src/services/DonationService.js](https://github.com/Giveth/giveth-dapp/blob/237a8d70c7d54e8f796a8972c189dd02c64a3a9a/src/services/DonationService.js#L129)
> 
> Line 129 in [237a8d7](/Giveth/giveth-dapp/commit/237a8d70c7d54e8f796a8972c189dd02c64a3a9a)
> 
>  return contract.mTransfer(encodedPledges, receiverId, {

Cool. Will do that now.

**Comment by gitcoinbot** [comment]
@iamonuwa Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by iamonuwa** [comment]
@gitcoinbot work in progress

@vojtechsimetka how do I get the new reviewer's details. Am asking this because the second feature is for the new reviewer to accept the review request. Any field on the data that indicates you have a review request?

**Comment by ceresstation** [comment]
Hey @vojtechsimetka just wanted to check to see if you and @iamonuwa had a chance to sync on the above question :)

**Comment by ceresstation** [comment]
Ah, yep I missed that, thanks for clarifying!

**Comment by ewingrj** [comment]
I just implemented milestone recipient changing. Probably would be useful to look at for this work.

https://github.com/Giveth/giveth-dapp/commit/6b2dce556dccd661bf2daa127bd74348a727c11e

Also, note that I would recommend implementing this on top of the feature/new-milestones branch. It removes the accept phase when changing the milestone reviewer.

**Comment by mroberts10** [comment]
@gitcoinbot open issue - can you help us find another person for this issue

**Comment by iamonuwa** [comment]
@mroberts10 I'll work on it and get it done now.

**Comment by GriffGreen** [comment]
@iamonuwa is there something we need to do? :-D?

**Comment by GriffGreen** [comment]
@iamonuwa just so you know, we made things easier... @ewingrj might have something to add

**Comment by ewingrj** [comment]
note, I edited the description a bit to reflect the current contracts

**Comment by GriffGreen** [comment]
@iamonuwa Are you still on this?

**Comment by GriffGreen** [comment]
@gitcoinbot I think we need a new person to tackle this

**Comment by GriffGreen** [comment]
Hey @iamonuwa  if you have any issues or are stuck on something feel free to join the riot chat and ask there: https://riot.im/app/#/room/!pJNSuPMvcrDttmJFvV:matrix.org?via=matrix.org&via=giveth.io&via=status.im

And you are also invited to our DApp meetings which happen at 6 pm Barcelona time every Friday at https://meet.jit.si/giveth-dapp ;-D

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by GriffGreen** [comment]
oooooo! https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401

It looks like @toya999 is on the case! Message us if you have any issues Toya! Also we have dapp meetings every Monday at 7pm Barcelona time at https://meet.jit.si/giveth-dapp if you want to join ;-)

Much love!

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)

**Comment by gitcoinbot** [comment]
@toya999 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/489/1401?snooze=100)
