### ISSUE TITLE
No one knows they're getting paid unless they are stalking the DApp!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#498]
I want (me and all users) to be notified when something happens for their address in the DApp. 
- When a milestone is created for you to receive. 
- When that milestone is reviewed or marked complete. 
- And AT THE VERY LEAST, when the eth is actually sent! 

But obviously the address I want to hold money in is not the address i want to put my private keys into the DApp for not-so-safe keeping. So thus, we end up with a bunch of "Anonymous User"s as recipients and only knowing the status of milestones that implicate us if we are closely following the DApp in our spare time. 

How can we solve this so that an email is sent to notify a user when something relevant to them happens in the DApp? 

Maybe create a form where they can fill in their email address, their name, and sign a message proving it's them?

**Comment by vojtechsimetka** [comment]
I will modify the description and title above. Anyways here is the task:

**Task:**
- [ ] Add to the User profile ability to store recipient addresses and optionally a list of emails who should be notified on each action. If no email is provided, the main profile email should be used. So it should take:
   - Name of the recipient account
   - Address
   - Optional list of emails
- [ ] Create email template in feathers for:
   - New milestone added for a recipient (first time the status goes to InProgress)
   - Milestone for a recipient was completed (when the status changes to Completed)
   - Milestone was paid out (when the status changes to Paid) - It should say that it may take more than 48 hours before the money is dispatched from the 
- [ ] Add the corresponding dispatch email calls to feathers https://github.com/Giveth/feathers-giveth/blob/develop/src/services/milestones/sendNotification.js

**Work needed estimate:**
10-15h

**Comment by perissology** [comment]
okay, I've made more notification emails for registered users.

1. If the recipient is different then the milestone manager, they will get a notification when the milestone is created
2. donors now get notifications when they make a donation
3. donation/delegation recipients now get a notification when they receive a donation
4. givers get a notification when they need to approve/reject a delegation
5. milestone recipients now get a notification when the milestone is paid

notification subscription management still needs to be implemented

**Comment by GriffGreen** [comment]
#536 can be looped into this :-D

**Comment by papermache** [comment]
@GriffGreen Any update.

**Comment by GriffGreen** [comment]
i still think this is connected to #536
