### ISSUE TITLE
Release 2018-11-22 bugs

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#535]
This is to transparently collect all the bugs in the next 2018-11-22 release that needs to be fixed. Please follow the [release precedure](https://docs.google.com/forms/d/e/1FAIpQLScaTkn-5-S6XJBDEasiZggjCJDtYchwGu22jwYXfdXX6ruqgw/viewform?usp=sf_link
), all tests are to be made on [release.giveth.io](release.giveth.io).

### Critical:
- [x] Donate button crashes Campaigns and DACs (fixed in cc02c1d6bb4cbba5af92cd7c7b9dcb2510d130d1)
- [x] Using the delegate button in Campaigns and Milestones gives empty state (fixed in 4fbf823fdbc89df59da74551947e97a25d84478e)
- [x] Some actions can be performed even if the user is not authenticated. E.g. actions in My Delegations, My Donations or from the "Delegate funds here" button. (fixed in b1a6c8206f6ab9602677be0058aa3920f28ae529)
- [x] Users are seemingly able to delegate money from Campaign's they don't own (see https://github.com/Giveth/giveth-dapp/issues/535#issuecomment-441817748, fixed in 41e9105620e22cd81a7574c62e1e2c898c86960d)

### Major:
- [x] Sometimes the DApp is stuck on "Loading". This is fixed with changing the MetaMask network but essentially means problem with the Web3Provider. (temporary fix in e675023eb4340118779c626178a50f5328610f3b)
- [x] Users "seemingly can" delegate money from wrong network (at least in the "Delegate funds here" button). Of course the smart contracts fail the TX. (fixed in 3ae0847c12b62cb02000202c10f5a8df7e2bbc86)
- [x] Rejecting delegation MetaMask transaction in the "Delegate funds here" button gives a positive notification. (fixed in d5cda1ae83b39593384493c0a59e084e29f4fefc)
- [x] Can not display IPFS uploaded video in the description video component (see https://github.com/Giveth/giveth-dapp/issues/535#issuecomment-441630132)
- [x] There are still sign-in issues with web3 provider. (fixed in 1542b9d769ea34153c445224334c61da212bd501)
- [x] Users are unable to edit proposed milestones (fixed in https://github.com/Giveth/feathers-giveth/commit/03d699fa01336e6fc32217422900c44e5e9b031e)

### Minor:
- [x] "Delegate funds here" button says: "Your donation has been confirmed! View transaction" (fixed in d5cda1ae83b39593384493c0a59e084e29f4fefc)
- [x] Navigating back from DACs/Campaigns goes to `/dacs` or `/campaigns` instead of `/` (fixed in d0692bea76bded73b0e4b7f677de307e1c5a80ee)
- [x] Buttons in modals footer are aligned vertically instead of horizontally (fixed in 5873fce068e10c298cab1bc672c7d0d84132a6d8)
- [x] Some modals have disable on click close outside of the modal area, however, there is no close button so the only way to close the modal is with `escape key` (fixed in 5873fce068e10c298cab1bc672c7d0d84132a6d8)
- [x] The email notifications for release have incorrect environment name - localhost (see https://github.com/Giveth/giveth-dapp/issues/535#issuecomment-441636710, fixed in feathers `config/[environment.json]` by appropriately changing the host)
- [ ] Sometimes MetaMask TXs don't popup, we should dim the screen and write a msg that user should check for MM TX.
- [x] Modification to "personal profile/website" in the user profile are not considered as modification and when trying to save don't produce TX. If updated along with other fields, the "personal profile" field is still empty when editing/viewing in the `/profile` route. (fixed in eff7340b7d874c2680fdae761bf07c2e2ed73465)

## Testing guidelines
To test the tokens you will need to request MiniME token from @vojtechsimetka (@vojtech:matrix.org) and add the token to your MetaMask account manually:
**Token Address**: `0xE690E380740a682E2b8CEAEa33584Ea2cb59849E`

### New features
- **Token Support** - DACs, Campaigns and Milestones can from now on use any whitelisted ERC20 tokens in addition to ETH
- **IPFS support** -  we store almost all the data in smart contracts or on IPFS removing the centralizing component of the feathers cache service (with the exception of Milestone data)
- **Removal of Giveth Wallet** - we removed the browser based Giveth Wallet and all the transaction are now made through MetaMask (or other web3 provider)
- **Video recording** - users are now able to upload or record videos directly from the DApp description
- **Pagination** - all the Manage pages are now paginated so you can finally inspect all your donations, delegations, campaigns and communities!

### Test especially
- Donations
- Delegations
- Milestone flow
- Video creating
- Wallet actions
- Getting paid :)

**Comment by Danibelle** [comment]
When I am in a campaign and use the <--campaigns back button, the top of the screen is cut off.
![image](https://user-images.githubusercontent.com/39466970/48961247-058f7300-ef41-11e8-818e-d5c003caaefa.png)

You can see at right the scroll bar is all the way up.

**Comment by vojtechsimetka** [comment]
Sometimes user's are unable to confirm delegation.

**Feathers error:**
```
2018-11-25 11:33: info: error: donations - Method: patch - Error
2018-11-25 11:33: error: Error {"type":"FeathersError","name":"NotAuthenticated","code":401,"className":"not-authenticated","errors":{},"timestamp":"2018-11-25T11:33:01.384Z"}
```

**Error in UI:**
<img width="510" alt="screen shot 2018-11-25 at 12 34 40" src="https://user-images.githubusercontent.com/7974813/48978632-946dce00-f0ae-11e8-9504-377d2c3d5fb1.png">

**Comment by vojtechsimetka** [comment]
Sometimes the DApp is stuck on "Loading" and it is only fixed with changing the web3 provider. The problem is likely with the MM but the Web3Provider makes the DApp stuck on loading.

**Comment by GriffGreen** [comment]
<img width="1121" alt="screen shot 2018-11-26 at 1 54 29 pm" src="https://user-images.githubusercontent.com/14945613/49015292-eed85e80-f182-11e8-9f54-2846d3b04345.png">
Video upload issue when creating it in the campaign

**Comment by vojtechsimetka** [comment]
@perissology This seems to be IPFS config problem, could you have a look?

**Comment by vojtechsimetka** [comment]
Email notifications have incorrect environment name.
<img width="231" alt="screen shot 2018-11-26 at 14 20 24" src="https://user-images.githubusercontent.com/7974813/49016519-a753d180-f186-11e8-82ae-bb7424189144.png">

**Comment by geleeroyale** [comment]
Found many issues - here is the rundown:

1 - "Your Profile URL" is not saved for me (in profile UI, its displaying fine if you visit my profile)
2 - When making a donation, its unclear to me if the modal has to stay open for second transaction - if YES would prefer to have a warning: "Do not close this until you signed the second transaction"
3 - Still confused about reviewers - should my MetaMask not have been added to the reviewers list on account creation as @vojtech mentioned in riot? What happens to our "old" reviewer list when the DApp gets updated?
4 - It is very confusing to me how metamask would be set correctly - are we really requesting users to change the network on the fly? And what happens if actions are taken with the wrong network set?
5 - "Your delegations" keeps saying: "You are not yet authenticated. Please sign-in to be able to perform actions"
6 - A donation I made to my own DAC is displayed in "Your donations" as donated to "GIVER geleeroyale" when it should say "COMMUNITY Fight Racism" - also that donation failed and still keeps on pending a few hours later(https://ropsten.etherscan.io/tx/0x4920444613dfe58237f08990b5513f688098e466512dd77f9f2ff80e660e5728) - retried with MiniMe instead of ETH and this time it worked and actually displayed the donation correctly as "DAC Fight racism" (https://ropsten.etherscan.io/tx/0x690c33af18f734ff200392705cb07c2abc7b5b2a9d78d586df49b856505ed080)
7 - After delegating my tokens from DAC to campaign I managed to break "My donations" view for a few minutes (Oh-Oh && You didn't make andy donations yet) - I think this was solved by a delegating tx finally having 6 confirmations
8 - Milestones seem to allow delegation of ETH only
9 - I want to donate on behalf of another address is confusing
10 - Donate: Is Donate via MyCrypto working? Sharing a donation link should be easier and maybe not tied to mycrypto.
11 - Re-Delegating funds from campaign to milestone did not seem to work (Oh Oh - unable to update the donation in feathers) - guess this is intended as a cause of 3day lockdown - however the lockdown should be somehow communicated!!!!! IN THE END IT WORKED DESPITE THE ERROR
12 - Editing Milestones only works from "My Milestones" - clicking edit icon on milestone detail view gives Oh-Oh error
13 - Editing Milestone (single and multiple expenses): Update image did not work - updating title or text worked
14 - Create single expense milestone with MiniMe funding gave Oh-Oh error - worked second time
15 - Editing proposed milestone gives weel of death on saving button - no changes are saved

**Comment by perissology** [comment]
> @perissology This seems to be IPFS config problem, could you have a look? See [tomeshnet/ipfs-live-streaming#44 (comment)](https://github.com/tomeshnet/ipfs-live-streaming/pull/44#discussion_r202365753) I just don't know where the IPFS service is running on.
> 
> @GriffGreen It created the video, the component just does not allow it to be displayed. That is a minor config problem :)
> 
> ```
> Refused to display 'https://ipfs.giveth.io/ipfs/QmVfzVZ7z9cA3eK1E4ks7LtrHRKoQKVR9hJdy6yVvfkcLM' in a frame because it set 'X-Frame-Options' to 'deny'.
> ```

I removed the "X-Frame-Options" header. Should be good to go now

**Comment by vojtechsimetka** [comment]
@geleeroyale Thanks for the testing! You've discovered quite some bugs :). Here is my response:

> 1 - "Your Profile URL" is not saved for me (in profile UI, its displaying fine if you visit my profile)

Oh the URL modifications are not being considered as modification! It does get saved to IPFS, but it does not display the newly saved value...

> 2 - When making a donation, its unclear to me if the modal has to stay open for second transaction - if YES would prefer to have a warning: "Do not close this until you signed the second transaction"

I don't know myself :/ Probably.

> 3 - Still confused about reviewers - should my MetaMask not have been added to the reviewers list on account creation as @vojtech mentioned in riot? What happens to our "old" reviewer list when the DApp gets updated?

Yes, the problem is that maybe the list is already tooo long so release actually does not show all of them. Plus the whitelist update requires hard refresh of the page. Not an issue for the release 2018-11-22 but something to consider for the release environment setting.

> 4 - It is very confusing to me how metamask would be set correctly - are we really requesting users to change the network on the fly? And what happens if actions are taken with the wrong network set?

The action taken with a wrong address (if the UI ever allows it) will just fail. And yeah users will change their networks manually. That being said it is very likely you are either just donating (and hence are always on mainnet) or you use any other functionality which is all on sidechain. There will probably not be many users taking both of these roles any time soon.

> 5 - "Your delegations" keeps saying: "You are not yet authenticated. Please sign-in to be able to perform actions"

Thanks this is UI bug. It does sign you but you need to refresh the page.

> 6 - A donation I made to my own DAC is displayed in "Your donations" as donated to "GIVER geleeroyale" when it should say "COMMUNITY Fight Racism" - also that donation failed and still keeps on pending a few hours later(https://ropsten.etherscan.io/tx/0x4920444613dfe58237f08990b5513f688098e466512dd77f9f2ff80e660e5728) - retried with MiniMe instead of ETH and this time it worked and actually displayed the donation correctly as "DAC Fight racism" (https://ropsten.etherscan.io/tx/0x690c33af18f734ff200392705cb07c2abc7b5b2a9d78d586df49b856505ed080)

The first donation actually did fail on the bridge side so the money was just given to you as the donor. Definitely needs to be better communicated but not a bug.

> 7 - After delegating my tokens from DAC to campaign I managed to break "My donations" view for a few minutes (Oh-Oh && You didn't make andy donations yet) - I think this was solved by a delegating tx finally having 6 confirmations

Yeah I noticed that but was never able to reproduce. Thanks for the steps I'll check it.

> 8 - Milestones seem to allow delegation of ETH only

I'll check.

> 9 - I want to donate on behalf of another address is confusing

Agree, but it will stay like that for the time being before better solution appears.

> 10 - Donate: Is Donate via MyCrypto working? Sharing a donation link should be easier and maybe not tied to mycrypto.

Yes it is possible. It actually created MyCrypto link to which it navigates you. The problem is that mycrypto "crypto newbie tutorial".....

> 11 - Re-Delegating funds from campaign to milestone did not seem to work (Oh Oh - unable to update the donation in feathers) - guess this is intended as a cause of 3day lockdown - however the lockdown should be somehow communicated!!!!! IN THE END IT WORKED DESPITE THE ERROR

It means you were not signed in the DApp but you are still able to make TX just not able to update the feathers cache. It is bug that it allowed you to still do to so, where exactly did you initiate the delegation action from?

> 12 - Editing Milestones only works from "My Milestones" - clicking edit icon on milestone detail view gives Oh-Oh error

Probably also not signed in. Any tips how to reproduce?

> 13 - Editing Milestone (single and multiple expenses): Update image did not work - updating title or text worked

This is actually a known issue, I'll try and fix it but should not block the release it is likely server configuration https://github.com/Giveth/giveth-dapp/issues/464

> 14 - Create single expense milestone with MiniMe funding gave Oh-Oh error - worked second time

Can you describe how to reproduce?

> 15 - Editing proposed milestone gives wheel of death on saving button - no changes are saved

A bug, thanks :)

**Comment by vojtechsimetka** [comment]
I was able to go to a Milestone and seemingly delegate money to it from the Milestone's original Campaign even though the campaign is not created by me.

https://release.giveth.io/campaigns/5bbe1bef907dbb7a361d026b

<img width="896" alt="screen shot 2018-11-26 at 23 04 47" src="https://user-images.githubusercontent.com/7974813/49045052-04c04080-f1d0-11e8-82b5-d303f3ffb5da.png">

**Comment by vojtechsimetka** [comment]
Thanks everyone for the testing, we have just released to production :). The only known "bug" (or rather not the best UX flow) will be fixed in the next release.

**Comment by mmohorko** [comment]
I can't click on milestones in Mozilla Firefox (version: 63.0.3 64 bit). See the screenshot. 

![photo_2018-11-29_14-00-37](https://user-images.githubusercontent.com/45455085/49223488-31967280-f3df-11e8-88dd-5f4ba248f633.jpg)

**Comment by vojtechsimetka** [comment]
@mmohorko Can you post the link here?

**Comment by vojtechsimetka** [comment]
@mmohorko Thanks for reporting the bug.

As for the error it is present in Firefox and Safari but if you try google it does work. So please for the time being use Chrome. I will investigate.

The not loading on your computer, just try and refresh. The first time you open the DApp there is something wrong. It is not our problem, it is problem with react-scripts and the npm serve package.
