### ISSUE TITLE
Delegating to milestones is very difficult from the manage page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#645]
So many milestones... i need to know what campaign they are coming from... 

ideally I could click a campaign and be given the choice to donate to the campaign itself, or to an individual milestone

**Comment by vojtechsimetka** [comment]
I am not sure I understand the issue here. The donate button is directly in the Campaign/Milestone. So it a delegate button. Can you clarify what is the tension exactly?

**Comment by GriffGreen** [comment]
there are too many milestones, and its sort of dangerous to just trust that you know which milestone you are looking for... i should have put in a picture... 

<img width="1142" alt="screen shot 2019-01-31 at 6 00 16 pm" src="https://user-images.githubusercontent.com/14945613/52070884-22b87180-2582-11e9-95b9-e1e17c5d0343.png">

**Comment by GriffGreen** [comment]
Ran into this again...

I forgot about the random little donations that were in the Giveth DAC from Thailand repayments... So UNKNOWINGLY I delegated 4 different pledges to Bowens milestone... The UX missing here is that I dont get to choose which of the donations get sent to this milestone...

In this case, i have to redo another donation on top, cause Bowen needs the cash and i dont think i can get lanski jeremy and kris to all commit their pledges
<img width="866" alt="screen shot 2019-02-13 at 12 04 17 am" src="https://user-images.githubusercontent.com/14945613/52674347-a4fe4980-2f23-11e9-8520-1770a3174712.png">

**Comment by GriffGreen** [comment]
Maybe if in this screen:
<img width="700" alt="screen shot 2019-02-13 at 12 12 20 am" src="https://user-images.githubusercontent.com/14945613/52674511-1c33dd80-2f24-11e9-9611-7ce73b99b63e.png">
It could have a "Choose which donations to send here" option... or even just check boxes next to the list of options or something :-D

**Comment by GriffGreen** [comment]
Ok so the comments above actually need to be in a different issue

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 120.0 DAI (120.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $58,409.50 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by GriffGreen** [comment]
I'm happy to do a quick call to explain what we need here.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now.
Please review their action plans below:


**1) [anshumanv](https://gitcoin.co/profile/anshumanv) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?mutate_worker_action=approve&worker=anshumanv) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?mutate_worker_action=reject&worker=anshumanv))_.**

Experienced React dev, I've already contributed a lot to this project, can get this done pretty quickly too.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).

**Comment by gitcoinbot** [comment]
@anshumanv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by GriffGreen** [comment]
Hey @anshumanv What is your schedule for some of these issues :-D?

**Comment by anshumanv** [comment]
Hey @GriffGreen struggling with the local setup now, will fix it soon. Can I know what exactly do we need here, in points if possible? Thanks! 😄

**Comment by gitcoinbot** [comment]
@anshumanv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@anshumanv due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by GriffGreen** [comment]
@anshumanv I'm not sure if there are points persay... but maybe i can describe the problem and the  desired design again and i can hope it will make sense!

The problem:
Right now there are just too many options in this drop down and its confusing cause you dont know what campaigns each milestone listed is in... you only get the title... so you might think you are delegating to a milestone in the giveth communications campaign, but actually you are delegating to the Bloom Campaign (this happened to me!)

My idea for a solution:

Make the drop down have 2 levels. The first level being the Campaign and then when you select a campaign, you get to select the milestones in that selected campaign PLUS an option to delegate directly to the campaign itself.

Thank you for pinging me in riot! Also ping @ElMejorge if you run into issues.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@anshumanv due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by nanspro** [comment]
@GriffGreen  the issue looks simple, i guess you want to change the ui by breaking it into two levels where on selecting one option from dropdown unlocks the milestones for that level in form of another dropdown.
The tricky part of the issue is it's setup :) , it's pretty confusing so i'll ask on riot about how to setup it from scratch and after that i'll apply through gitcoin.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 days, 1 hour from now.
Please review their action plans below:


**1) [xiaods](https://gitcoin.co/profile/xiaods) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?mutate_worker_action=approve&worker=xiaods) | [reject worker](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?mutate_worker_action=reject&worker=xiaods))_.**

i guess you want to change the ui by breaking it into two levels where on selecting one option from dropdown unlocks the milestones for that level in form of another dropdown. please let me know your design, i will work on it when you approved.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).

**Comment by xiaods** [comment]
any update?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 day, 15 hours ago.
Please review their action plans below:


**1) [xiaods](https://gitcoin.co/profile/xiaods) has been approved to start work.**

i guess you want to change the ui by breaking it into two levels where on selecting one option from dropdown unlocks the milestones for that level in form of another dropdown. please let me know your design, i will work on it when you approved.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).

**Comment by xiaods** [comment]
working on it now.

**Comment by xiaods** [comment]
hi team, i have already setup the environment done, but the project not give me initial 5 ANT token on Ganache chain, i am contract on team. waiting team response. thanks .

**Comment by xiaods** [comment]
@GriffGreen i have already evaluate the process, but found some exceptions, could you please give more suggestion.

proposal:
Make the drop down have 2 levels. The first level being the Campaign and then when you select a campaign, you get to select the milestones in that selected campaign PLUS an option to delegate directly to the campaign itself.

problem:
but currently the campaign and milestone is already filter one-one relation

**Comment by gitcoinbot** [comment]
@xiaods Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by xiaods** [comment]
@gitcoinbot  i am working on it. block on some reviewer not review and give next process.

**Comment by gitcoinbot** [comment]
@xiaods Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by xiaods** [comment]
@gitcoinbot yes, blocking on no response from develop team.

**Comment by xiaods** [comment]
@gitcoinbot team is feedback, i will continue work on it.

**Comment by gitcoinbot** [comment]
@xiaods Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by gitcoinbot** [comment]
@xiaods Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 120.0 DAI (120.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@xiaods](https://gitcoin.co/profile/xiaods)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/Giveth/giveth-dapp/pull/738) by @xiaods

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $104,586.64 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by xiaods** [comment]
waiting owner review.

**Comment by ElMejorge** [comment]
Sorry for the late response but the PR is fine and fixes the problem. Thank you for your contribution

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 120.0 DAI (120.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @xiaods.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/645/2481)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $83,986.07 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
