### ISSUE TITLE
Getting refund/canceling is too easy

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#80]
Several non-recoverable actions are too easy to perform in the DApp. These are:

- Cancel Milestone
- Delete Milestone
- Cancel Campaign
- Refund donation

The buttons for these actions should be visible, but the confirmation should be more difficult like deleting a Github Repository.

**Task:**

- [ ] Create popup component for non-trivial actions that will ask to copy the title of the Milestone/Campaign or the amount of donation (first 5 digits)
- [ ] Replace the confirmation flow for these actions with the newly created component

**Example how it looks on Github**
<img width="494" alt="screen shot 2018-07-10 at 23 40 31" src="https://user-images.githubusercontent.com/7974813/42539217-b1be3b1e-849a-11e8-816b-e7dba00a7311.png">
<img width="494" alt="screen shot 2018-07-10 at 23 40 31" src="https://user-images.githubusercontent.com/7974813/42539218-b4872482-849a-11e8-8702-b23e7c1e0e68.png">

**Comment by vojtechsimetka** [comment]
@anshumanv @vs77bb How do you like this one? More are coming :).

**Comment by anshumanv** [comment]
This is super interesting! :open_mouth: 

I'll surely love working on this. :tada: 
cc @vs77bb :sparkles:

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 DAI (300.0 USD @ $1.0/DAI) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $30,142.51 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 4 weeks, 1 day from now. Please review their questions below:


1. [anshumanv](https://gitcoin.co/profile/anshumanv) has started work. 	
 * Q: Nothing so far, I'll follow up if I'm stuck somewhere, excited!

**Comment by vojtechsimetka** [comment]
Hey @anshumanv sorry for late response:

> I'm no longer to make the donations since I think some changes are done recently and wallet doesn't have anymore ETH to test maybe? It ways insufficient balance when I try to make donations.

Yes we have change the DApp so that you have to use external web3 provider to donate. All you need to do is import one of the keystores to metamask.

> I see the options to cancel milestone/campaign, where's the option to delete milestone? 

Milestones can be deleted only when they are proposed (meaning you "create" a milestone in campaign that is not made by you) and they can be deleted only until they are accepted by the Campaign lead.

**Comment by anshumanv** [comment]
>Yes we have change the DApp so that you have to use external web3 provider to donate. All you need to do is import one of the keystores to metamask.

Okay, lost track of the recent changes, will try this.

> Milestones can be deleted only when they are proposed (meaning you "create" a milestone in campaign that is not made by you) and they can be deleted only until they are accepted by the Campaign lead.

Makes sense, I'll try playing around with it. :+1:

Thanks for the help again @vojtechsimetka  :smile:

**Comment by vojtechsimetka** [comment]
Yeah that works :). Can you also `highlight` (just like this) the par that needs to be copied?

**Comment by gitcoinbot** [comment]
@anshumanv Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823?snooze=1) | [3 days](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823?snooze=3) | [5 days](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823?snooze=5) | [10 days](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823?snooze=10) | [100 days](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823?snooze=100)

**Comment by anshumanv** [comment]
I'll complete this today.

**Comment by vs77bb** [comment]
How's this going @anshumanv? Hope you're doing well 🙂

**Comment by anshumanv** [comment]
Hey @vs77bb I'm at my best and hoping for you the same. This is almost done and a WIP PR is at https://github.com/Giveth/giveth-dapp/pull/443 the task is completed, just need some refactoring, will be doing this tomorrow. :+1: :sparkle: Thanks for checking it up!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 300.0 DAI (300.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@anshumanv](https://gitcoin.co/profile/anshumanv)



@vs77bb please take a look at the submitted work:
* [PR](https://github.com/Giveth/giveth-dapp/pull/443) by @anshumanv

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/Giveth/giveth-dapp/80/823).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $28,962.82 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
